tasks:
  - before: echo 'npm install -g generator-jhipster'
    command: |
      npm install -g generator-jhipster

vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - pivotal.vscode-spring-boot