tasks:
  - init: |
      echo 'TODO: build project'
    command: |
      echo 'TODO: start app'

vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - pivotal.vscode-spring-boot